#cloud-config

# Install docker, microk8s with snap
snap:
  commands:
    - [install, docker]
    - [install, microk8s, --classic, --channel=1.28]

# create the docker group
groups:
  - docker

# Setup default ubuntu user & enable SSH access
users:
  - name: ubuntu
    groups: sudo, docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      # - <your ssh rsa public key>

# make sure firewall is not a problem
runcmd:
  - sudo iptables -P FORWARD ACCEPT
  - sudo microk8s enable dns
  - sudo microk8s enable registry
  - sudo microk8s enable ingress
  - sudo microk8s enable cert-manager
