POST localhost:4000/register
content-type: application/json

{
  "email": "quan.lu@arent3d.com",
  "password": "Abc@1234"
}

POST http://localhost:4000/register
Content-Type: application/json;charset=UTF-8

{
  "email": "ludinhquan@gmail.com",
  "password": "Q?abc1"
}

POST localhost:4000/login
content-type: application/json

{
  "email": "test@mailinator.com",
  "password": "Quan?abc1"
}

POST localhost:4000/login
Content-Type: application/json

{
  "email": "quan.lu@arent3d.com",
  "password": "Quan?abc1"
}

POST localhost:4000/logout
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzY4MDQwMC1jMTVlLTQyY2UtYWE4My1jZjgyM2Y4NDI5ZjYiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTc2MTI1OTAsImV4cCI6MTY5NzY5ODk5MH0.iyNaGzmg9RfsZF_rk7BewXDr2nVCSTWaHXY_MFVNfoY

GET localhost:4000/me
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzY4MDQwMC1jMTVlLTQyY2UtYWE4My1jZjgyM2Y4NDI5ZjYiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTc2MTI1OTAsImV4cCI6MTY5NzY5ODk5MH0.iyNaGzmg9RfsZF_rk7BewXDr2nVCSTWaHXY_MFVNfoY

PATCH localhost:4000/user
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzY4MDQwMC1jMTVlLTQyY2UtYWE4My1jZjgyM2Y4NDI5ZjYiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTc2MTI1OTAsImV4cCI6MTY5NzY5ODk5MH0.iyNaGzmg9RfsZF_rk7BewXDr2nVCSTWaHXY_MFVNfoY

{
  "name": "Lu Dinh Quan"
}

POST localhost:4000/reset-password
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTczMjkwMjMsImV4cCI6MTY5NzQxNTQyM30.mG0aiQiX279gC2vrF1gbUSFRmNmrbihk_c5jrp-5cU0

{
  "oldPassword": "Abc@1234",
  "newPassword": "dada"
}

POST localhost:4000/email-confirmation/confirm
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1ZGluaHF1YW5AZ21haWwuY29tIiwiaWF0IjoxNjk3MTg5NDMwLCJleHAiOjE2OTcyNzU4MzB9.j_8t_-c87rT5Qg08_cCGBu5ZqxTKqlOhofTlpMbCyZI"
}

POST localhost:4000/email-confirmation/resend-confirmation-link
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTczMjkwMjMsImV4cCI6MTY5NzQxNTQyM30.mG0aiQiX279gC2vrF1gbUSFRmNmrbihk_c5jrp-5cU0

POST http://localhost:4000/google-authentication
Accept: */*
Accept-Language: en-US,en
Connection: keep-alive
Content-Type: text/plain;charset=UTF-8
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="118", "Brave";v="118", "Not=A?Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"

{
  "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlB3RUU1YS1DUFlkMUJCV19MT05heSJ9.eyJpc3MiOiJodHRwczovL2Rldi1neHBibm84dHBtMXdteGpiLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDM1NzQwNDYwNjEzMjgzMTUxNiIsImF1ZCI6WyJodHRwczovL2Rldi1neHBibm84dHBtMXdteGpiLnVzLmF1dGgwLmNvbS9hcGkvdjIvIiwiaHR0cHM6Ly9kZXYtZ3hwYm5vOHRwbTF3bXhqYi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjk3MjA4OTE0LCJleHAiOjE2OTcyOTUzMTQsImF6cCI6ImpqSTU1RVFCNDBjZDZuT3pYUmlUMmwzN1FWQVpMOUg5Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.nzKgjuzK72-rcCJ3YNH4xeNh1Wcfphzf770OvCKBiQEUr26nDklQf38pWiMnb9nvNkO3JUipLFJHdUxKD5W-MB_DkUD2rXhDc9eeuq9t8a_RC8fn1FMJRIB0zeH3qYPkv971vVbPXG0EnNQoQQ1QIQa4iJOX_imnPySERXrwek0-G9K0kWbHLMPBcDDLprCWNp8PZM46kQ82N1aue-JgveYX9-TKl5w_1tHYrGbaYfD9vuF5Nhb_LtdjBnwrK_AYUaEKwOB0nAlGaiNw_b-e-sjmWaFK9rWoLdekoFfDhZ0TsVxye--3SlQEvbNgY0-Fj3YyUSR_UCHKJlp3gCfxoA"
}

GET localhost:4000/dashboard/summary
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzY4MDQwMC1jMTVlLTQyY2UtYWE4My1jZjgyM2Y4NDI5ZjYiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTc2MTI1OTAsImV4cCI6MTY5NzY5ODk5MH0.iyNaGzmg9RfsZF_rk7BewXDr2nVCSTWaHXY_MFVNfoY

GET localhost:4000/dashboard/users
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzY4MDQwMC1jMTVlLTQyY2UtYWE4My1jZjgyM2Y4NDI5ZjYiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTc2MTI1OTAsImV4cCI6MTY5NzY5ODk5MH0.iyNaGzmg9RfsZF_rk7BewXDr2nVCSTWaHXY_MFVNfoY
