global:
  image:
    registry: localhost:32000
    pullPolicy: IfNotPresent
    tag: latest
  env: {}

postgresql:
  enabled: true
  fullnameOverride: postgresql
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: dashboard
  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 32345

client:
  enabled: true
  env:
    VITE_BASE_URL: https://demo.draweditor.com/api
    VITE_AUTH0_DOMAIN: dev-gxpbno8tpm1wmxjb.us.auth0.com
    VITE_AUTH0_CLIENT_ID: jjI55EQB40cd6nOzXRiT2l37QVAZL9H9
    VITE_AUTH0_AUDIENCE: https://dev-gxpbno8tpm1wmxjb.us.auth0.com/api/v2/

server:
  enabled: true
  env:
    DATABASE_URL: "postgresql://postgres:postgres@postgresql:5432/dashboard?schema=public&sslmode=prefer&connect_timeout=300"

    AUTH0_DOMAIN: dev-gxpbno8tpm1wmxjb.us.auth0.com

    CLIENT_URL: https://demo.draweditor.com
    SERVER_URL: https://demo.draweditor.com/api

    JWT_ACCESS_TOKEN_SECRET: access@1234A$
    JWT_ACCESS_TOKEN_EXPIRATION_TIME: 30m

    JWT_REFRESH_TOKEN_SECRET: refresh@1234$
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: 7d

    JWT_VERIFICATION_TOKEN_SECRET: verification@1234A$
    JWT_VERIFICATION_TOKEN_EXPIRATION_TIME: 1d

    EMAIL_VERIFICATION_URL: https://demo.draweditor.com/email-confirmation
    EMAIL_VERIFICATION_TIME_RESEND: 60

ingress:
  enabled: true
  className: public
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-demo
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: demo.draweditor.com
      paths:
        - name: server
          path: /api/(.*)
          pathType: Prefix
          port: 4000
        - name: client
          path: /?(.*)
          pathType: Prefix
          port: 3000
  tls:
    - secretName: ies-tls
      hosts:
        - demo.draweditor.com
