global:
  image:
    registry:
    pullPolicy:
    tag:
  env: {}

postgresql:
  fullnameOverride: postgresql
  primary:
    service:
      type: ClusterIP

server:
  env:
    JWT_ACCESS_TOKEN_SECRET:
    JWT_ACCESS_TOKEN_EXPIRATION_TIME:

    JWT_REFRESH_TOKEN_SECRET:
    JWT_REFRESH_TOKEN_EXPIRATION_TIME:

    JWT_VERIFICATION_TOKEN_SECRET:
    JWT_VERIFICATION_TOKEN_EXPIRATION_TIME:

    SMTP_SERVER:
    SMTP_USERNAME:
    SMTP_PASSWORD:
